export const softwareLogos: { [key: string]: { [key: string]: string } } = {
  'web-dev': {
    'React': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    'Next.js': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
    'WordPress': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-plain.svg',
    'Shopify': 'https://cdn.worldvectorlogo.com/logos/shopify.svg',
    'Node.js': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
    'TypeScript': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
  },
  'custom-apps': {
    'React': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    'Node.js': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
    'Python': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
    'MongoDB': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg',
    'PostgreSQL': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
    'Docker': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
  },
  'mobile-apps': {
    'React Native': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    'Flutter': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg',
    'Swift': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg',
    'Kotlin': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg',
    'Firebase': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg',
    'AWS': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg',
  },
  'desktop-software': {
    'Electron': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/electron/electron-original.svg',
    'Python': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
    'C++': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg',
    'Java': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg',
    'Qt': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/qt/qt-original.svg',
    'Visual Studio': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/visualstudio/visualstudio-plain.svg',
  },
  'server-solutions': {
    'Linux': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg',
    'Ubuntu': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ubuntu/ubuntu-plain.svg',
    'CentOS': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/centos/centos-original.svg',
    'Nginx': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nginx/nginx-original.svg',
    'Apache': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apache/apache-original.svg',
    'Docker': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
  },
  'cloud-solutions': {
    'AWS': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg',
    'Azure': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    'Google Cloud': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg',
    'Kubernetes': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg',
    'Terraform': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg',
    'Docker': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
  },
  'network-infrastructure': {
    'Cisco': 'https://cdn.worldvectorlogo.com/logos/cisco-2.svg',
    'Ubiquiti': 'https://cdn.worldvectorlogo.com/logos/ubiquiti-networks.svg',
    'Fortinet': 'https://cdn.worldvectorlogo.com/logos/fortinet.svg',
    'VMware': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vmware/vmware-original.svg',
    'OpenStack': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/openstack/openstack-original.svg',
    'Ansible': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ansible/ansible-original.svg',
  },
  'data-storage': {
    'AWS S3': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg',
    'Google Cloud Storage': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg',
    'Azure Blob': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    'MongoDB': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg',
    'PostgreSQL': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
    'Redis': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg',
  },
  'integration': {
    'Zapier': 'https://cdn.worldvectorlogo.com/logos/zapier.svg',
    'Microsoft 365': 'https://cdn.worldvectorlogo.com/logos/microsoft-365.svg',
    'Google Workspace': 'https://cdn.worldvectorlogo.com/logos/google-workspace.svg',
    'Slack': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/slack/slack-original.svg',
    'Salesforce': 'https://cdn.worldvectorlogo.com/logos/salesforce.svg',
    'HubSpot': 'https://cdn.worldvectorlogo.com/logos/hubspot.svg',
  },
  'support': {
    'Zendesk': 'https://cdn.worldvectorlogo.com/logos/zendesk.svg',
    'Freshdesk': 'https://cdn.worldvectorlogo.com/logos/freshdesk.svg',
    'Intercom': 'https://cdn.worldvectorlogo.com/logos/intercom.svg',
    'TeamViewer': 'https://cdn.worldvectorlogo.com/logos/teamviewer.svg',
    'AnyDesk': 'https://cdn.worldvectorlogo.com/logos/anydesk.svg',
    'Jira': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg',
  },
  'ai-ml': {
    'TensorFlow': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg',
    'PyTorch': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg',
    'Python': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
    'OpenAI': 'https://cdn.worldvectorlogo.com/logos/openai.svg',
    'Hugging Face': 'https://cdn.worldvectorlogo.com/logos/hugging-face.svg',
    'Scikit-learn': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scikit-learn/scikit-learn-original.svg',
  },
  'data-analytics': {
    'Python': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
    'R': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/r/r-original.svg',
    'Tableau': 'https://cdn.worldvectorlogo.com/logos/tableau-software.svg',
    'Power BI': 'https://cdn.worldvectorlogo.com/logos/power-bi.svg',
    'Apache Spark': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachespark/apachespark-original.svg',
    'Jupyter': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jupyter/jupyter-original.svg',
  },
  'crm': {
    'Salesforce': 'https://cdn.worldvectorlogo.com/logos/salesforce.svg',
    'HubSpot': 'https://cdn.worldvectorlogo.com/logos/hubspot.svg',
    'Zoho': 'https://cdn.worldvectorlogo.com/logos/zoho.svg',
    'Pipedrive': 'https://cdn.worldvectorlogo.com/logos/pipedrive.svg',
    'Microsoft Dynamics': 'https://cdn.worldvectorlogo.com/logos/microsoft-dynamics-365.svg',
    'SugarCRM': 'https://cdn.worldvectorlogo.com/logos/sugarcrm.svg',
  },
  'erp': {
    'SAP': 'https://cdn.worldvectorlogo.com/logos/sap.svg',
    'Oracle': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    'Microsoft Dynamics': 'https://cdn.worldvectorlogo.com/logos/microsoft-dynamics-365.svg',
    'NetSuite': 'https://cdn.worldvectorlogo.com/logos/netsuite.svg',
    'Odoo': 'https://cdn.worldvectorlogo.com/logos/odoo.svg',
    'Sage': 'https://cdn.worldvectorlogo.com/logos/sage.svg',
  },
  'hrm': {
    'Workday': 'https://cdn.worldvectorlogo.com/logos/workday.svg',
    'BambooHR': 'https://cdn.worldvectorlogo.com/logos/bamboohr.svg',
    'ADP': 'https://cdn.worldvectorlogo.com/logos/adp.svg',
    'Gusto': 'https://cdn.worldvectorlogo.com/logos/gusto.svg',
    'Paychex': 'https://cdn.worldvectorlogo.com/logos/paychex.svg',
    'Zenefits': 'https://cdn.worldvectorlogo.com/logos/zenefits.svg',
  },
  'scm': {
    'SAP': 'https://cdn.worldvectorlogo.com/logos/sap.svg',
    'Oracle': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    'Manhattan Associates': 'https://cdn.worldvectorlogo.com/logos/manhattan-associates.svg',
    'JDA Software': 'https://cdn.worldvectorlogo.com/logos/jda-software.svg',
    'Infor': 'https://cdn.worldvectorlogo.com/logos/infor.svg',
    'Kinaxis': 'https://cdn.worldvectorlogo.com/logos/kinaxis.svg',
  },
  'branding': {
    'Adobe Creative Suite': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/adobe/adobe-original.svg',
    'Figma': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg',
    'Sketch': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sketch/sketch-original.svg',
    'Canva': 'https://cdn.worldvectorlogo.com/logos/canva.svg',
    'InVision': 'https://cdn.worldvectorlogo.com/logos/invision.svg',
    'Marvel': 'https://cdn.worldvectorlogo.com/logos/marvel.svg',
  },
  'ui-ux': {
    'Figma': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg',
    'Adobe XD': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xd/xd-plain.svg',
    'Sketch': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sketch/sketch-original.svg',
    'InVision': 'https://cdn.worldvectorlogo.com/logos/invision.svg',
    'Marvel': 'https://cdn.worldvectorlogo.com/logos/marvel.svg',
    'Principle': 'https://cdn.worldvectorlogo.com/logos/principle.svg',
  },
  'graphic-design': {
    'Adobe Photoshop': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg',
    'Adobe Illustrator': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg',
    'Adobe InDesign': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/indesign/indesign-plain.svg',
    'Canva': 'https://cdn.worldvectorlogo.com/logos/canva.svg',
    'Affinity Designer': 'https://cdn.worldvectorlogo.com/logos/affinity-designer.svg',
    'GIMP': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gimp/gimp-original.svg',
  },
  'digital-marketing': {
    'Google Analytics': 'https://cdn.worldvectorlogo.com/logos/google-analytics.svg',
    'Google Ads': 'https://cdn.worldvectorlogo.com/logos/google-ads.svg',
    'Facebook Ads': 'https://cdn.worldvectorlogo.com/logos/facebook.svg',
    'Mailchimp': 'https://cdn.worldvectorlogo.com/logos/mailchimp.svg',
    'HubSpot': 'https://cdn.worldvectorlogo.com/logos/hubspot.svg',
    'Hootsuite': 'https://cdn.worldvectorlogo.com/logos/hootsuite.svg',
  },
  'strategy': {
    'Google Analytics': 'https://cdn.worldvectorlogo.com/logos/google-analytics.svg',
    'SEMrush': 'https://cdn.worldvectorlogo.com/logos/semrush.svg',
    'Ahrefs': 'https://cdn.worldvectorlogo.com/logos/ahrefs.svg',
    'Moz': 'https://cdn.worldvectorlogo.com/logos/moz.svg',
    'Google Search Console': 'https://cdn.worldvectorlogo.com/logos/google-search-console.svg',
    'Google Trends': 'https://cdn.worldvectorlogo.com/logos/google-trends.svg',
  },
  'ppc': {
    'Google Ads': 'https://cdn.worldvectorlogo.com/logos/google-ads.svg',
    'Facebook Ads': 'https://cdn.worldvectorlogo.com/logos/facebook.svg',
    'LinkedIn Ads': 'https://cdn.worldvectorlogo.com/logos/linkedin.svg',
    'Twitter Ads': 'https://cdn.worldvectorlogo.com/logos/twitter.svg',
    'TikTok Ads': 'https://cdn.worldvectorlogo.com/logos/tiktok.svg',
    'Microsoft Advertising': 'https://cdn.worldvectorlogo.com/logos/microsoft-advertising.svg',
  },
  'email-hosting': {
    'Microsoft 365': 'https://cdn.worldvectorlogo.com/logos/microsoft-365.svg',
    'Google Workspace': 'https://cdn.worldvectorlogo.com/logos/google-workspace.svg',
    'Zoho Mail': 'https://cdn.worldvectorlogo.com/logos/zoho.svg',
    'ProtonMail': 'https://cdn.worldvectorlogo.com/logos/protonmail.svg',
    'Tutanota': 'https://cdn.worldvectorlogo.com/logos/tutanota.svg',
    'Fastmail': 'https://cdn.worldvectorlogo.com/logos/fastmail.svg',
  },
  'printing': {
    'Adobe InDesign': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/indesign/indesign-plain.svg',
    'Adobe Illustrator': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg',
    'QuarkXPress': 'https://cdn.worldvectorlogo.com/logos/quarkxpress.svg',
    'CorelDRAW': 'https://cdn.worldvectorlogo.com/logos/coreldraw.svg',
    'Affinity Publisher': 'https://cdn.worldvectorlogo.com/logos/affinity-publisher.svg',
    'Canva': 'https://cdn.worldvectorlogo.com/logos/canva.svg',
  },
  'startup-package': {
    'WordPress': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-plain.svg',
    'Shopify': 'https://cdn.worldvectorlogo.com/logos/shopify.svg',
    'Google Workspace': 'https://cdn.worldvectorlogo.com/logos/google-workspace.svg',
    'Canva': 'https://cdn.worldvectorlogo.com/logos/canva.svg',
    'Mailchimp': 'https://cdn.worldvectorlogo.com/logos/mailchimp.svg',
    'Google Analytics': 'https://cdn.worldvectorlogo.com/logos/google-analytics.svg',
  },
  'small-business-package': {
    'React': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    'Node.js': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
    'Microsoft 365': 'https://cdn.worldvectorlogo.com/logos/microsoft-365.svg',
    'HubSpot': 'https://cdn.worldvectorlogo.com/logos/hubspot.svg',
    'Adobe Creative Suite': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/adobe/adobe-original.svg',
    'AWS': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg',
  },
  'ultimate-package': {
    'React': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    'Next.js': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
    'AWS': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg',
    'Salesforce': 'https://cdn.worldvectorlogo.com/logos/salesforce.svg',
    'Adobe Creative Suite': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/adobe/adobe-original.svg',
    'Google Analytics': 'https://cdn.worldvectorlogo.com/logos/google-analytics.svg',
  },
}; 